sudo: false
language: node_js
node_js:
  - "10"
before_script:
  - "wget -O caddy.tar.gz 'https://github.com/mholt/caddy/releases/download/v0.11.5/caddy_v0.11.5_linux_amd64.tar.gz'"
  - "tar xvf caddy.tar.gz"
  - "./caddy &"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
cache: yarn
branches:
  only:
    - "gh-pages"
