language: node_js
sudo: false
node_js:
  - "7"
  - "node"
before_script:
  - "wget -O caddy.tar.gz 'https://caddyserver.com/download/build?os=linux&arch=amd64&features='"
  - "tar xvf caddy.tar.gz"
  - "./caddy &"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
cache: yarn
